# Main workflow to orchestrate all other workflows
name: main workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yaml
